# =============================================================================
# Fluent Bit - Proxmox Task Log Input
# Path: /etc/fluent-bit/conf.d/proxmox.conf
# Deploy on: Proxmox nodes only (always combine with linux.conf)
# Variables: host_ip, vlan, o2_user, o2_passwd (set in fluent-bit.conf)
# =============================================================================

[INPUT]
    Name              tail
    Tag               proxmox.*
    Path              /var/log/pve/*.log
    Read_from_Head    Off
    DB                /var/log/fluent-bit-proxmox.db
    Skip_Long_Lines   On

[FILTER]
    Name          record_modifier
    Match         proxmox.*
    Record        host      ${HOSTNAME}
    Record        log_type  proxmox
    Record        vlan      ${vlan}
    Record        host_ip   ${host_ip}

[OUTPUT]
    Name          http
    Match         proxmox.*
    Host          ${o2_host}
    Port          443
    TLS           On
    TLS.Verify    On
    URI           /api/${o2_org}/proxmox/_json
    Format        json
    HTTP_User     ${o2_user}
    HTTP_Passwd   ${o2_passwd}
    compress      gzip
    Retry_Limit   5
